defaults.url=https://sentry.io/
# Fill in your Sentry org slug, or set SENTRY_ORG environment variable in CI
defaults.org=YOUR_SENTRY_ORG
# Fill in your Sentry project slug, or set SENTRY_PROJECT environment variable in CI
defaults.project=YOUR_SENTRY_PROJECT
# Uncomment and set your auth token, or use SENTRY_AUTH_TOKEN environment variable in CI
# auth.token=YOUR_SENTRY_AUTH_TOKEN